# https://github.com/actions/javascript-action

name: 'Report LCOV'
description: 'Report the code coverage from LCOV files'
author: 'Zennon Gosalvez'
inputs:
  coverage-files:
    description: 'The coverage files to scan. For example, `coverage/lcov.*.info`'
    required: true
  artifact-name:
    description: 'The GitHub artifact name of the generated HTML report. For example, `code-coverage-report`. _Note:_ When downloading, it will be extracted in an `html` directory'
    required: true
  minimum-coverage:
    description: 'The minimum coverage to pass the check. Optional. Default: `0` (always passes)'
    default: 0
  github-token:
    description: 'Github token to publish artifacts. Optional. Default: ``'
  github-comment-token:
    description: 'Git token to use to publish comment with coverage summary. Optional. Default: ``'
  working-directory:
    description: 'The working directory containing the source files referenced in the LCOV files. Optional. Default: `./`'
runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
branding:
  icon: umbrella
  color: purple